<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2017, 2025 Red Hat Inc and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Red Hat Inc
     Eurotech
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>kura-artemis.parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>org.eclipse.kura.broker.artemis.core</artifactId>
    <version>${org.eclipse.kura.broker.artemis.core.version}</version>
    <packaging>eclipse-plugin</packaging>

    <properties>
        <jctools-core.version>4.0.5</jctools-core.version>
        <caffeine.version>3.2.0</caffeine.version>
        <activemq-artemis-native.version>2.0.0</activemq-artemis-native.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <configuration>
                            <outputDirectory>${project.basedir}/lib</outputDirectory>
                            <stripVersion>true</stripVersion>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-server</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-commons</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-core-client</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-jdbc-store</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-jms-client</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-jms-server</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-journal</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-selector</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-service-extensions</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-mqtt-protocol</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-amqp-protocol</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-stomp-protocol</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.activemq</groupId>
                                    <artifactId>activemq-artemis-native</artifactId>
                                    <version>${activemq-artemis-native.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.artemis</groupId>
                                    <artifactId>artemis-log-annotation-processor</artifactId>
                                    <version>${org.apache.activemq.artemis.upstream.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.jctools</groupId>
                                    <artifactId>jctools-core</artifactId>
                                    <version>${jctools-core.version}</version>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>com.github.ben-manes.caffeine</groupId>
                                    <artifactId>caffeine</artifactId>
                                    <version>${caffeine.version}</version>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
